/*
* Copyright (c) 2000-2015 Samsung Electronics Co., Ltd All Rights Reserved
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
*/


#ifndef __MP_DEFINES_H__
#define __MP_DEFINES_H__

/* definitions for EDC build */
#define MP_COLOR_BG_BLACK				8 8 8 255
#define MP_COLOR_BG_BLACK_TRANSPARENT		        8 8 8 0
#define FOCUS_BORDER		8 8 8 8

#ifndef MP_IMAGE_ROTATE_FEATURE
//efine MP_IMAGE_ROTATE_FEATURE
#endif

//#define MP_FEATURE_APP_IN_APP

/* main size */
#define MAIN_W			480
#define MAIN_H			800
//#define PLAYVIEW_H		706
#define PLAYVIEW_H		620
#define MENUBOX_H		/*90*/56
#define PROGRESSBOX_H	67

/* bg color */
#define DEFAULT_BG_COLOR	248 246 239 255

/* font name*/
#define FONT_STYLE_ROMAN "TIZEN:style=Roman"
#define FONT_STYLE_MEDIUM "TIZEN:style=Medium"
#define FONT_STYLE_BOLD "TIZEN:style=Bold"

#define FONT_NAME "system_content"		//should be replaced to FONT_CONTENT_NAME
#define FONT_TITLE_NAME "system_title"	//"system_title"
#define FONT_CONTENT_NAME "system_content"	//"system_content"
#define FONT_SUBCONTENT_NAME "system_subcontent"	//"system_subcontent"

/* soft key*/
#define SOFTKEY_SY (722/MAIN_H)

#define MP_NAVI_BAR_H 	(35)
/* player info box*/
#define INFO_BOX_SY ((/*595*/634 - MP_NAVI_BAR_H)/MAIN_H)
/* play control box*/
#define CTL_BOX_HEIGHT 120/*86*/
#define CTL_BOX_SY /*((714 -10)/MAIN_H)*/705/MAIN_H
#define CTL_REW_SX (115/MAIN_W)
#define CTL_REW_EX (165/MAIN_W)
#define CTL_REW_SY (20/CTL_BOX_HEIGHT)
#define CTL_REW_EY (70/CTL_BOX_HEIGHT)
#define CTL_PAUSE_SX (215/MAIN_W)
#define CTL_PAUSE_EX (265/MAIN_W)
#define CTL_FF_SX (315/MAIN_W)
#define CTL_FF_EX (365/MAIN_W)


/* play menu box*/
#define HD_MENU_BOX_H 96
#define HD_MENU_BOX_W 720

#define HD_MENU_H 76
#define HD_MENU_W 76
#define HD_MENU_PAD_TOP 10
#define HD_MENU_PAA_LEFT 34

#define HD_MENU_PAD_MENU 212

#define MENU_SY HD_MENU_PAD_TOP/HD_MENU_BOX_H
#define MENU_EY (HD_MENU_PAD_TOP+HD_MENU_H)/HD_MENU_BOX_H

#define MENU_REP_ALL_SX HD_MENU_PAA_LEFT/HD_MENU_BOX_W
#define MENU_REP_ALL_EX (HD_MENU_PAA_LEFT+HD_MENU_W)/HD_MENU_BOX_W
#define MENU_SHUFFLE_SX (HD_MENU_PAA_LEFT+HD_MENU_W+HD_MENU_PAD_MENU)/HD_MENU_BOX_W
#define MENU_SHUFFLE_EX (HD_MENU_PAA_LEFT+HD_MENU_W*2+HD_MENU_PAD_MENU)/HD_MENU_BOX_W
#define MENU_FAVORITE_SX (HD_MENU_PAA_LEFT+HD_MENU_W*2+HD_MENU_PAD_MENU*2)/HD_MENU_BOX_W
#define MENU_FAVORITE_EX (HD_MENU_PAA_LEFT+HD_MENU_W*3+HD_MENU_PAD_MENU*2)/HD_MENU_BOX_W

/* play progress box*/

#define PROGRESS_BOX_HEIGHT 67
#define PROGRESS_BOX_SY (414/PLAYVIEW_H)
#define PROGRESS_BOX_EY (507/PLAYVIEW_H)
#define PROGRESS_BG_SX (80/MAIN_W)
#define PROGRESS_BG_SY (27/PROGRESS_BOX_HEIGHT)
#define PROGRESS_BG_EX (400/MAIN_W)
#define PROGRESS_BG_EY (41/PROGRESS_BOX_HEIGHT)
#define PROGRESS_BAR_L_EX (36/MAIN_W)
#define PROGRESS_BAR_R_EX (45/MAIN_W)
#define PROGRESS_PLAYING_SX (10/MAIN_W)
#define PROGRESS_PLAYING_SY (376/MAIN_H)
#define PROGRESS_PLAYING_EX (60/MAIN_W)
#define PROGRESS_PLAYING_EY (426/MAIN_H)
#define PROGRESS_TEXT_PLAYING_SX (30/MAIN_W)
#define PROGRESS_TEXT_PLAYING_SY (460/MAIN_H)
#define PROGRESS_TEXT_PLAYING_EX (130/MAIN_W)
#define PROGRESS_TEXT_PLAYING_EY (500/MAIN_H)
#define PROGRESS_TEXT_TOTAL_SX (350/MAIN_W)
#define PROGRESS_TEXT_TOTAL_EX (450/MAIN_W)
#define AUTO_REP_SX (205/MAIN_W)
#define AUTO_REP_SY (452/MAIN_H)
#define AUTO_REP_EX (275/MAIN_W)
#define AUTO_REP_EY (488/MAIN_H)

/* play Title*/
#define PLAY_INFO_HEIGHT 189
#define TRACK_TITLE_SX (15/MAIN_W)
#define TRACK_TITLE_SY (18/PLAY_INFO_HEIGHT)
#define ALBUM_TITLE_SY ((18+40)/PLAY_INFO_HEIGHT)
#define ARTIST_TITLE_SY ((18+40+36)/PLAY_INFO_HEIGHT)
#define ARTIST_TITLE_EY ((18+40+36+34)/PLAY_INFO_HEIGHT)

/* favorite */
#define FAVORITE_SX (420/MAIN_W)
#define FAVORITE_EX (470/MAIN_W)
#define FAVORITE_SY (10/PLAY_INFO_HEIGHT)
#define FAVORITE_EY (60/PLAY_INFO_HEIGHT)

/* volume*/
#define VOLUME_BTN_SX (12/MAIN_W)
#define VOLUME_BTN_SY (19/CTL_BOX_HEIGHT)
#define VOLUME_BTN_EX (65/MAIN_W)
#define VOLUME_BTN_EY CTL_REW_EY
#define VOLUME_POPUP_WIDTH	262
#define VOLUME_POPUP_HEIGHT	424
#define VOLUME_POPUP_SX	(108/MAIN_W)
#define VOLUME_POPUP_EX	(370/MAIN_W)
#define VOLUME_POPUP_SY	(94/PLAYVIEW_H)
#define VOLUME_POPUP_EY	(568/PLAYVIEW_H)

#define VOLUME_POPUP_TITLE_SY	(16 / VOLUME_POPUP_HEIGHT)
#define VOLUME_POPUP_TITLE_EY	(56 / VOLUME_POPUP_HEIGHT)
#define VOLUME_POPUP_ICON_SX		(107 / VOLUME_POPUP_WIDTH)
#define VOLUME_POPUP_ICON_EX		(157 / VOLUME_POPUP_WIDTH)
#define VOLUME_POPUP_ICON_SY 	(62 / VOLUME_POPUP_HEIGHT)
#define VOLUME_POPUP_ICON_EY		(112 / VOLUME_POPUP_HEIGHT)
#define VOLUME_POPUP_SLIDER_SX	(68/ VOLUME_POPUP_WIDTH)
#define VOLUME_POPUP_SLIDER_EX	(194/ VOLUME_POPUP_WIDTH)
#define VOLUME_POPUP_SLIDER_SY	(130/ VOLUME_POPUP_HEIGHT)
#define VOLUME_POPUP_SLIDER_EY	(400/ VOLUME_POPUP_HEIGHT)

#define VOLUME_PROGRESS_BOX_SX (400/MAIN_W)
#define VOLUME_PROGRESS_BOX_SY (25/MAIN_H)
#define VOLUME_PROGRESS_BOX_EY (507/MAIN_H)
#define VOLUME_PROGRESS_BG_SX (433/MAIN_W)
#define VOLUME_PROGRESS_BG_SY (59/MAIN_H)
#define VOLUME_PROGRESS_BG_EX (447/MAIN_W)
#define VOLUME_PROGRESS_BG_EY (479/MAIN_H)

#define VOLUME_PROGRESS_TOP (62/MAIN_H)
#define VOLUME_PROGRESS_BOTTOM (482/MAIN_H)
#define VOLUME_PROGRESS_LEFT (433/MAIN_W)
#define VOLUME_PROGRESS_RIGHT (447/MAIN_W)

/*auto repeat*/
#define REPEAT_BG_SX (150/MAIN_W)
#define REPEAT_BG_SY (158/MAIN_H)
#define REPEAT_BG_EX (330/MAIN_W)
#define REPEAT_BG_EY (258/MAIN_H)

#define REPEAT_A_BG_SY (307/MAIN_H)
#define REPEAT_A_BG_EY (392/MAIN_H)
#define REPEAT_B_BG_SY (410/MAIN_H)
#define REPEAT_B_BG_EY (507/MAIN_H)

/*information*/
#define INFO_TITLEBG_SY (18/MAIN_H)
#define INFO_TITLEBG_EY (147/MAIN_H)
#define INFO_MAINALBUMIMAGE_SX (10/MAIN_W)
#define INFO_MAINALBUMIMAGE_SY (44/MAIN_H)
#define INFO_MAINALBUMIMAGE_EX (90/MAIN_W)
#define INFO_MAINALBUMIMAGE_EY (124/MAIN_H)
#define INFO_MAINTITLE_SX (100/MAIN_W)
#define INFO_MAINTITLE_SY (53/MAIN_H)
#define INFO_MAINARTIST_SY (89/MAIN_H)

#define INFO_TITLE_SX (20/MAIN_W)
#define INFO_TITLE_SY (154/MAIN_H)
#define INFO_TITLE_EY (190/MAIN_H)
#define INFO_ALBUMART_SY (239/MAIN_H)
#define INFO_ALBUMART_EY (269/MAIN_H)

#define INFO_BTN_SX (415/MAIN_W)
#define INFO_BTN_SY VOLUME_BTN_SY
#define INFO_BTN_EX (468/MAIN_W)
#define INFO_BTN_EY VOLUME_BTN_EY

#define MAX_W_LEFT MAIN_H-197
#define OFFSET_TITLE -13
#define OFFSET_TITLE_BOTTOM -14

/*
#define NAVIFRAME_TITLE_H_INC 100
#define NAVIFRAME_SEGMENT_TITLE_H_INC 136
#define NAVIFRAME_OH_OPENED_H_INC 106
#define NAVIFRAME_OH_CONTENT_H_INC 74
#define NAVIFRAME_OH_PADDING_INC 16
#define NAVIFRAME_OH_ARROW_SIZE_INC 19 14
#define NAVIFRAME_OH_OPENED_DOUBLE_H_INC 196
#define NAVIFRAME_PREV_BTN_W_INC 124
#define NAVIFRAME_TITLE_FUNC_BTN_PADDING_W_INC 10
#define NAVIFRAME_TITLE_FUNC_BTN_SIZE_INC 124 80
#define NAVIFRAME_TEXT_PADDING_INC 144
#define NAVIFRAME_TEXT_PADDING_MORE_BUTTON_INC 278
#define NAVIFRAME_TEXT_PADDING_ICON_VISIBLE_INC 186
#define NAVIFRAME_TITLE_SEGMENT_H_INC 74
#define NAVIFRAME_TITLE_SEGMENT_FONT_SIZE_INC 28
#define NAVIFRAME_TITLE_SEGMENT_TEXT_H_INC 50
#define NAVIFRAME_TITLE_FONT_SIZE_INC 36
#define NAVIFRAME_ICON_SIZE_INC 32 32
#define NAVIFRAME_ICON_PADDING_INC 16 0
#define NAVIFRAME_CONTROLBAR_PADDING_INC 5
*/

#define CONTROLBAR_LARGE_HEIGHT_INC 122
//#define CONTROLBAR_SMALL_HEIGHT_INC 102
#define CONTROLBAR_WIDTH_INC 122

#define MP_NAVIFRAME_CONTROLBAR_H 114

#define MP_BUTTON_PRESSED_NAME "Tizen_touch.wav"

#endif /* __MP_DEFINES_H__ */
