/*
* Copyright (c) 2000-2015 Samsung Electronics Co., Ltd All Rights Reserved
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
*/

#ifndef __MP_RESOURCE_H_
#define __MP_RESOURCE_H_

#define     STR_MP_TRACKS         	("IDS_MUSIC_OPT_TRACKS")
#define     STR_MP_PLAYLISTS		("IDS_MUSIC_TAB4_PLAYLISTS")
#define     STR_MP_ALBUMS			("IDS_MUSIC_TAB4_ALBUMS")
#define     STR_MP_ARTISTS			("IDS_MUSIC_TAB4_ARTISTS")
#define     STR_MP_RENAME	        ("IDS_MUSIC_POP_RENAME")
#define     STR_MP_EDIT_TITLE	    ("IDS_MUSIC_OPT_EDIT_TITLE")
#define     STR_MP_REORDER          ("IDS_MUSIC_OPT_REORDER")
#define     STR_MP_FOLDERS			("IDS_MUSIC_ITAB4_FOLDERS")
#define     STR_MP_GENRES			("IDS_MUSIC_ITAB4_GENRES")
#define     STR_MP_SQUARE			("IDS_MUSIC_TAB4_MUSIC_SQUARE")
#define     STR_MP_SAVE_AS          ("IDS_MUSIC_SK_SAVE_AS")
#define     STR_MP_MOST_PLAYED		("IDS_MUSIC_BODY_MOST_PLAYED")
#define     STR_MP_RECENTLY_ADDED	("IDS_MH_MBODY_RECENTLY_ADDED_M_SONG")
#define     STR_MP_RECENTLY_PLAYED	("IDS_MUSIC_BODY_RECENTLY_PLAYED")
#define     STR_MP_FAVOURITES       ("IDS_IV_BODY_FAVOURITE")

#define     STR_MP_ADD_TO_FAVOURITES           	("IDS_MUSIC_OPT_ADD_TO_FAVOURITES")
#define		STR_MP_UNFAVOURITES			("Unfavourites")
#define     STR_MP_ADD_TO_PLAYLIST  ("IDS_MUSIC_BODY_ADD_TO_PLAYLIST")
#define 	STR_MP_SETTINGS		("IDS_COM_BODY_SETTINGS")
#define 	STR_MP_DETAILS			"IDS_MUSIC_HEADER_DETAILS"
#define 	STR_MP_END		("IDS_COM_BODY_END")
#define 	STR_MP_EDIT			("IDS_COM_BODY_EDIT")
#define 	STR_MP_SET_AS			("IDS_MUSIC_BODY_SET_AS_M_RINGTONE")
#define		STR_MP_POP_SET		"IDS_MUSIC_POP_SET"
#define		STR_MP_POP_CALLER_RINGTONE_SAVED		"IDS_PB_POP_CALLER_RINGTONE_SAVED"

#define 	STR_MP_SHARE		"IDS_MUSIC_SK_SHARE"
#define 	STR_MP_ADD_TO_PERSONAL_PAGE		"IDS_ST_POP_MOVE_TO_PERSONAL_STORAGE"
#define 	STR_MP_REMOVE_FROM_PERSONAL_PAGE		"IDS_ST_POP_MOVE_TO_NORMAL_STORAGE"
#define MP_PERSONAL_ITEM_MOVE_TO			"IDS_ST_POP_THE_SELECTED_ITEM_WILL_BE_MOVED_TO_PS"
#define MP_PERSONAL_ITEMS_MOVE_TO			"IDS_ST_POP_THE_SELECTED_ITEMS_WILL_BE_MOVED_TO_PS"
#define MP_PERSONAL_DONT_ASK_AGAIN			"IDS_MUSIC_BUTTON_DONT_ASK_AGAIN"

#define 	STR_MP_CREATE_PLAYLIST		"IDS_MUSIC_OPT_CREATE_PLAYLIST"
#define 	STR_MP_TURN_PHONE_OVER	"IDS_MUSIC_BODY_TURN_PHONE_OVER_TO_MUTE_INCOMING_CALLS_MESSAGE_ALERTS_AND_ALARMS"
#define 	STR_MP_DONT_ASK_AGAIN	"IDS_MUSIC_BUTTON_DONT_ASK_AGAIN"
#define	STR_MP_ENABLE_MOTION		"IDS_MUSIC_BUTTON_ENABLE_MOTION"
#define	STR_MP_DELETE 			("IDS_MUSIC_OPT_DELETE")
#define	STR_MP_CANCEL				"IDS_MUSIC_SK_CANCEL"
#define	STR_MP_OK					"IDS_COM_SK_OK"
#define STR_MP_CLOSE				"IDS_COM_BODY_CLOSE"
#define STR_MP_UPDATED				"IDS_COM_POP_UPDATED"
#define STR_MP_DOWNLOADING			"IDS_COM_POP_DOWNLOADING"
#define STR_MP_NO_SONGS			"IDS_MUSIC_HEADER_NO_SONGS"
#define STR_MP_NO_TRACKS			"IDS_MUSIC_BODY_NO_TRACKS"
#define STR_MP_NO_ARTISTS                "IDS_MUSIC_BODY_NO_ARTISTS"
#define STR_MP_NO_ALBUMS           "IDS_MUSIC_BODY_NO_ALBUMS"
#define STR_PLAYER_VIEW_VOLUME	"IDS_MUSIC_OPT_VOLUME"
#define STR_PLAYER_VIEW_QUEUE	"IDS_MUSIC_MBODY_QUEUE"
#define STR_PLAYER_VIEW_REPEAT	"IDS_MUSIC_OPT_REPEAT"
#define STR_PLAYER_VIEW_SHUFFLE	"IDS_MUSIC_BODY_SHUFFLE"
#define STR_MP_OPEN_PLAYLIST	"IDS_MUSIC_SK_OPEN_PLAYLIST"
#define STR_MP_VIEW_AS			"IDS_MUSIC_SK_VIEW_AS"
#define STR_MP_LIST				"IDS_MUSIC_SK_LIST"
#define STR_MP_THUMBNAIL		"IDS_MUSIC_OPT_THUMBNAIL"
#define STR_MP_DONE				"IDS_COM_POP_DONE"
#define STR_MP_NAVI_DONE		"IDS_TPLATFORM_ACBUTTON_DONE_ABB"
#define STR_MP_NAVI_CANCEL		"IDS_TPLATFORM_ACBUTTON_CANCEL_ABB"
#define STR_MP_REMOVE			"IDS_MUSIC_OPT_REMOVE"
#define STR_MP_REMOVING			"IDS_MUSIC_POP_REMOVING"
#define STR_MP_REMOVED			"IDS_COM_POP_REMOVED"
#define STR_MP_DELETED			"IDS_COM_POP_DELETED"
#define STR_MP_ADD				"IDS_MUSIC_BUTTON_MOVE"
#define STR_MP_ADDIND				"IDS_ST_BUTTON_MOVING_ING"
#define STR_MP_ADD_TO			"IDS_MUSIC_OPT_ADD_TO"
#define STR_MP_GO_TO_LIBRARY	"IDS_MUSIC_OPT_GO_TO_LIBRARY"
#define STR_MP_CREATE			"IDS_MUSIC_HEADER_CREATE"
#define STR_MP_NOT_USED			"IDS_MUSIC_BODY_NOT_USED"
#define STR_MP_SEARCH			"IDS_MUSIC_OPT_SEARCH_ABB"
#define STR_MP_TAKE_PICTURE		"IDS_MUSIC_OPT_TAKE_PICTURE"
#define STR_MP_CHANGE_IMAGE		"IDS_MUSIC_OPT_CHANGE_IMAGE"
#define STR_MP_VIEW 			"IDS_MUSIC_SK_VIEW"
#define STR_MP_MAKE_AVAILABLE_OFFLINE "IDS_MUSIC_BODY_MAKE_AVAILABLE_OFFLINE"
#define STR_MP_NEAR_BY_DEVICE	"IDS_MUSIC_BODY_NEARBY_DEVICES"
#define STR_MP_EDIT_IMAGE		"IDS_MUSIC_SK2_EDIT_IMAGE"
#define STR_MP_THIS_FILE_IS_UNABAILABLE "IDS_MUSIC_BODY_A_NETWORK_CONNECTION_IS_REQUIRED_TO_PLAY_THIS_FILE_CHECK_YOUR_NETWORK_CONNECTION_AND_TRY_AGAIN"
#define STR_MP_THIS_WILL_BE_DELETE_FORM_SERVER "IDS_MUSIC_BODY_THIS_WILL_DELETE_THE_FILE_FROM_THE_SERVER_AND_ANY_CONNECTED_DEVICES_AS_WELL"
#define STR_MP_ALL_CONTENTS		"IDS_MUSIC_OPT_ALL_CONTENT_ABB2"
#define STR_MP_CONTENTS_IN_PHONE	"IDS_MUSIC_OPT_CONTENT_ON_PHONE_ABB"
#define STR_MP_CONTENTS_IN_CLOUD	"IDS_MUSIC_OPT_DROPBOX_CONTENT_ABB"
#define STR_MP_PLAY_ALL				"IDS_MUSIC_OPT_MOREMENU_PLAY_ALL"
#define STR_MP_NO_PLAYLISTS			"IDS_MUSIC_BODY_NO_PLAYLISTS"
#define STR_MP_FILE_TYPE_NOT_SUPPORTED	"IDS_MUSIC_POP_FILE_TYPE_NOT_SUPPORTED"
#define STR_MP_1_ALBUM_1_SONG			"IDS_MUSIC_BODY_1_ALBUM_1_TRACK"
#define STR_MP_1_ALBUM_PD_SONGS			"IDS_MUSIC_BODY_1_ALBUM_PD_TRACKS"
#define STR_MP_PD_ALBUMS_PD_SONGS		"IDS_MUSIC_BODY_PD_ALBUMS_PD_TRACKS"
#define STR_MP_PD_SONGS		                "IDS_MUSIC_BODY_PD_TRACKS_ABB"
#define STR_MP_1_SONG		                "IDS_MUSIC_BODY_1_TRACK"
#define STR_MP_UPDATING_ING				"IDS_MUSIC_POP_UPDATING_ING"
#define STR_MP_TABS             "IDS_BR_SK_TABS"

#define     	STR_MP_INTERNET           	"IDS_COM_BODY_INTERNET"
#define 	STR_MP_RELATED_VIDEOS		"IDS_MUSIC_BODY_RELATED_VIDEOS"
#define 	STR_MP_CREDITS				"IDS_MUSIC_BODY_CREDITS"
#define		STR_MP_MEDIA_INFO			"IDS_MUSIC_BODY_DETAILS_MEADIA_INFO"
#define 	STR_MP_TRACK_LIST			"IDS_MUSIC_HEADER_TRACK_LIST"
#define 	STR_MP_SIMILAR_ALBUMS		"IDS_MUSIC_HEADER_SIMILAR_ALBUMS"
#define 	STR_MP_REVIEW				"IDS_MUSIC_BODY_REVIEW"
#define		STR_MP_POP_EXISTS               "IDS_MUSIC_POP_ALREADY_EXISTS"
#define STR_NH_COM_POPUP_CHARACTERS_MAXNUM_REACHED  ("IDS_COM_POP_MAXIMUM_NUMBER_OF_CHARACTERS_REACHED")
#define		STR_MP_POP_PLAYLIST_EXISTS              "IDS_MH_BODY_THE_PLAYLIST_NAME_PS_IS_ALREADY_IN_USE"
#define		STR_MP_POP_ADDED_TO_PLAYLIST            "IDS_MH_TPOP_PD_TRACKS_ADDED_TO_PLAYLIST"
#define		STR_MP_POP_ADDED_1_TO_PLAYLIST            "IDS_MH_TPOP_1_TRACK_ADDED_TO_PLAYLIST"

#define STR_MOOD         	"IDS_MUSIC_BODY_MOODS"
#define STR_YEAR   			"IDS_MUSIC_BUTTON_YEARS"
#define STR_ADDED       	"IDS_COM_OPT_ADDED"
#define STR_TIME         	"IDS_COM_BODY_TIME"
#define STR_OLD         	"IDS_MUSIC_BODY_OLD"
#define STR_NEW         	"IDS_COM_SK_NEW"
#define STR_NEW_FOR_SQUARE "IDS_MUSIC_BODY_NEW_M_LATEST"
#define STR_EXCITING		        "IDS_MUSIC_BODY_EXCITING_M_ADJECTIVE"
#define STR_CALM			"IDS_MUSIC_BODY_CALM_M_ADJECTIVE"
#define STR_PASSION			"IDS_MUSIC_BODY_PASSION_M_MOOD"
#define STR_JOY				"IDS_MUSIC_BODY_JOY_M_MOOD"

#define STR_MP_SQUARE_HELP_TEXT_1			"IDS_MUSIC_BODY_MUSIC_SQUARE_ANALYSES_THE_CHARACTERISTICS_OF_MUSIC_FILES_STORED_ON_YOUR_DEVICE_AND_AUTOMATICALLY_CREATES_PLAYLISTS_MSG"
#define STR_MP_SQUARE_HELP_TEXT_2			"IDS_MUSIC_BODY_PLAY_TRACKS_WITH_SIMILAR_CHARACTERISTICS_BY_SELECTING_A_SQUARE_ON_THE_SCREEN"
#define STR_MP_SQUARE_HELP_TEXT_3			"IDS_MUSIC_BODY_VIEW_PLAYLIST_DETAILS_BY_TAPPING_AND_HOLDING_THE_SQUARE_CURRENTLY_BEING_PLAYED"
#define STR_MP_SQUARE_NOT_ENOUGH_SONG_PD	"IDS_MUSIC_POP_NOT_ENOUGH_MUSIC_FILES_TO_PLAY_IN_MUSIC_SQUARE_AT_LEAST_PD_MUSIC_FILES_REQUIRED"
#define STR_MP_SQUARE_LIBRARY_UPDATED_NEED	"IDS_MUSIC_POP_YOU_WILL_NEED_TO_UPDATE_THE_LIBRARY_IF_NEW_SONGS_HAVE_BEEN_ADDED"
#define STR_MP_SQUARE_HELP_TEXT		"Music square analyses the characteristics of music files stored on your device and automatically creates playlists based on these characteristics. You can create a playlist of similar tracks by tapping cells in the music square."

#define STR_RECENTLY_ADDED   	"IDS_MUSIC_OPT_LISTBY_RECENTLY_ADDED"
#define STR_MP_SMART_VOLUME	"IDS_MUSIC_BODY_SMART_VOLUME_ABB"
#define STR_MP_SMART_VOLUME_IS_ENABLED			"IDS_MUSIC_HEADER_SMART_VOLUME_IS_ENABLED"
#define STR_MP_VOLUME_WILL_BE_ADJUSTED_TO_PD	"IDS_MUSIC_BODY_THE_VOLUME_OF_ALL_TRACKS_WILL_BE_ADJUSTED_TO_LEVEL_PD"
#define STR_MP_SEARCH_BY 			"IDS_MUSIC_OPT_SEARCH_BY"
#define STR_MP_THIS_SOUND_EFFECT_WORKS_IN			"IDS_MUSIC_POP_THIS_SOUND_EFFECT_WORKS_IN_EARPHONE_MODE_ONLY"
#define STR_MP_COM_REFRESH				"IDS_COM_SK_REFRESH"
#define STR_MP_SELECT_DEVICE				"IDS_MUSIC_HEADER_SELECT_DEVICE"

#define STR_MP_SHOW_LYRICS	        "IDS_MUSIC_OPT_SHOW_LYRICS"
#define STR_MP_HIDE_LYRICS			"IDS_MUSIC_OPT_HIDE_LYRICS"
#define STR_MP_LYRICS				"IDS_MUSIC_OPT_LYRICS_ABB"
#define STR_MP_ALL_THUMBNAIL_VIEW       "IDS_MUSIC_OPT_THUMBNAIL_VIEW"

#define STR_MP_MY_SOUND	                        "IDS_MUSIC_BODY_ADAPT_SOUND_ABB"
#define STR_MP_ALL_LIST_VIEW                    "IDS_MUSIC_OPT_LIST_VIEW"
#define STR_MP_PLAY_VIA_GROUP_PLAY              "IDS_MUSIC_OPT_PLAY_VIA_GROUP_PLAY"
#define STR_MP_CONNECTION_INFO		        "IDS_MUSIC_OPT_CONNECTION_INFO_ABB"
#define STR_MP_POPUP_MORE_INFO			"IDS_MH_OPT_MORE_INFO_ABB"
#define STR_MP_POPUP_ADD_TO_FAVORITE		"IDS_MUSIC_POP_TRACK_ADDED_TO_FAVOURITES"
#define STR_MP_POPUP_REMOVE_FROM_FAVORITE	"IDS_MUSIC_OPT_REMOVE_FROM_FAVOURITES"
#define STR_MP_MUSIC	                        "IDS_MUSIC_BODY_MUSIC"
#define STR_MP_SHUFFLE_PD_TRACKS                "IDS_MUSIC_HEADER_SHUFFLE_PD_TRACKS"
#define STR_MP_SHUFFLE_1_TRACK						"IDS_MUSIC_HEADER_SHUFFLE_1_TRACK"
#define STR_MP_SCAN_FOR_NEARBY_DEVICE           "IDS_MUSIC_OPT_SCAN_FOR_NEARBY_DEVICES"

#define STR_MP_UNABLE_TO_PLAY_DURING_CALL			"IDS_MUSIC_TPOP_UNABLE_TO_PLAY_MUSIC_DURING_CALLS"
#define STR_MP_UNABLE_TO_PLAY_ERROR_OCCURED		"IDS_MUSIC_POP_UNABLE_TO_PLAY_ERROR_OCCURRED"

#define STR_MP_SQURE_NO_SONGS						"IDS_MUSIC_HEADER_NO_SONGS"
#define STR_MP_UPDATING_FAILED						"IDS_MUSIC_POP_MUSICPLAYER_UPDATING_FAILED"

#define STR_MP_MY_DEVICE			       "IDS_MUSIC_BODY_MY_DEVICE"
#define MP_DETAIL_FORMAT_STR              "IDS_MUSIC_BODY_FORMAT"
#define MP_DETAIL_LOCATION_STR            "IDS_MUSIC_BODY_MUSIC_LOCATION"
#define MP_DETAIL_SAMPLING_STR            "IDS_MUSIC_BODY_SAMPLING_RATE"
#define MP_DETAIL_COPYRIGHT_STR           "IDS_MUSIC_BODY_COPYRIGHT"
#define MP_DETAIL_AUTHOR_STR              "IDS_MUSIC_BODY_AUTHOR"
#define MP_DETAIL_RECORDED_DATE_STR       "IDS_MUSIC_BODY_DETAILS_RECORDING_DATE"
#define MP_DETAIL_LENGTH_STR              "IDS_MUSIC_TMBODY_LENGTH"
#define MP_DETAIL_ALBUM_STR               "IDS_MUSIC_BODY_ALBUM"
#define MP_DETAIL_ARTIST_STR              "IDS_MUSIC_BODY_ARTIST"
#define MP_DETAIL_TITLE_STR               "IDS_MUSIC_BODY_TITLE"
#define MP_DETAIL_NUMBER_STR              "IDS_MUSIC_BODY_TRACK_NUMBER"
#define MP_DETAIL_BITDEPTH_STR            "IDS_MUSIC_BODY_BIT_DEPTH"
#define MP_DETAIL_SIZE_STR                "IDS_MUSIC_BODY_SIZE"


#define STR_MP_TILTE_SELECT_ITEM                        "IDS_MUSIC_HEADER_SELECT_ITEMS"
#define STR_MP_TITLE_SAVE_AS_PLAYLIST		        "IDS_MUSIC_OPT_SAVE_AS_PLAYLIST"

#define STR_MP_NO_PURCHASED_CONTENTS                    "IDS_MUSIC_BODY_NO_PURCHASED_CONTENT"
#define STR_MP_BTN_GOTO_STORE                           "IDS_MUSIC_OPT_GO_TO_STORE"
#define STR_MP_AFTER_YOU_ADD_TRACKS		"IDS_MUSIC_BODY_AFTER_YOU_ADD_TRACKS_TO_THIS_DEVICE_THEY_WILL_BE_SHOWN_HERE"
#define STR_MP_AFTER_YOU_DOWNLOAD_TRACKS                "IDS_MUSIC_BODY_AFTER_YOU_DOWNLOAD_TRACKS_FROM_MUSIC_THEY_WILL_BE_SHOWN_HERE"
#define STR_MP_AFTER_ADD_TRACKS_HELP                "IDS_MUSIC_POP_AFTER_YOU_ADD_TRACKS_TO_MUSIC_ON_YOUR_MOBILE_DEVICE_THEY_WILL_BE_SHOWN_HERE"

#define STR_MP_AFTER_YOU_DOWNLOAD_TRACKS_FOLDER_WILL_BE_SHOWN		"IDS_MUSIC_BODY_AFTER_YOU_DOWNLOAD_TRACKS_FOLDERS_WILL_BE_SHOWN"
#define STR_MP_YOU_CAN_ADD_TRACKS_THE_PLAYLIST_PD       "IDS_MUSIC_BODY_AFTER_YOU_ADD_TRACKS_TO_PS_THEY_WILL_BE_SHOWN_HERE"
#define STR_MP_ADD_TRACKS 			        "IDS_MUSIC_OPT_ADD"

#define	STR_MP_AFTER_YOU_ADD_TRACK_TO_FAVOURITE		"IDS_MUSIC_BODY_AFTER_YOU_ADD_TRACKS_TO_YOUR_FAVOURITES_THEY_WILL_BE_SHOWN_HERE"
#define	STR_MP_AFTER_YOU_PLAY_TRACKS_THEY_WILL_BE_SHOWN	"IDS_MUSIC_BODY_AFTER_YOU_PLAY_TRACKS_THEY_WILL_BE_SHOWN_HERE"

#define STR_SEARCH_GUIDE                        "IDS_MUSIC_HEADER_SEARCH_MUSIC_ABB"

#define STR_MP_CONNECTED_DEVICE_LOWER           "IDS_MUSIC_HEADER_CONNECTED_DEVICES"
#define STR_MP_CHANGE_PLAYER                    "IDS_DLNA_OPT2_CHANGE_PLAYER"
#define STR_MP_DEFAULT_PLAYLIST_GROUP_TITLE		"IDS_MUSIC_MBODY_DEFAULT_PLAYLISTS"
#define STR_MP_MY_PLAYLIST_GROUP_TITLE			"IDS_MUSIC_HEADER_MY_PLAYLISTS_ABB"
#define STR_MP_MY_PLAYLIST                      "IDS_MUSIC_BODY_MY_PLAYLIST_PS"
#define STR_MP_SELECT_ITEMS                     "IDS_MF_HEADER_PD_SELECTED"

#define STR_MP_DISCOGRAPHY			"IDS_MUSIC_BODY_DISCOGRAPHY"
#define STR_MP_BIOGRAPHY			"IDS_MUSIC_BODY_BIOGRAPHY"
#define STR_MP_NO_FOLDERS			"IDS_MUSIC_BODY_NO_FOLDERS"
#define STR_MP_NO_DEVICES                       "IDS_MUSIC_BODY_NO_DEVICES"
#define STR_MP_AVAILABLE_DEVICES                "IDS_MUSIC_HEADER_AVAILABLE_DEVICES_ABB"

#define STR_MP_YOU_CAN_CONTROL		"IDS_MUSIC_BODY_YOU_CAN_CONTROL_MUSIC_PLAYER_WITH_THE_VOICE_COMMANDS_P1SS_P2SS_P3SS_P4SS_P5SS_AND_P6SS"

#define STR_MP_BTN_RESET			"IDS_COM_BODY_RESET_A"
#define STR_MP_SPEAKER				"IDS_MUSIC_OPT_SPEAKER"
#define STR_MP_HEADPHONES			"IDS_MUSIC_OPT_HEADPHONES_ABB"

#define STR_MP_SOUNDALIVE                          "IDS_MUSIC_OPT_SOUNDALIVE"
#define STR_MP_UNABLE_FF_RW                     "IDS_MUSIC_POP_UNABLE_TO_USE_FAST_FORWARD_AND_REWIND_WHEN_NEARBY_DEVICES_ARE_ENABLED"
#define STR_MP_LIBRARY_UPDATE                         "IDS_MUSIC_BODY_LIBRARY_UPDATE"
#define STR_MP_DO_NOT_SHOW_AGAIN                   "IDS_MUSIC_BODY_DO_NOT_SHOW_AGAIN"
#define STR_MP_VARIOUS_ARTISTS                   "IDS_MUSIC_BODY_VARIOUS_ARTISTS"

#define STR_MP_NOT_ENOUGH_SPACE_ERROR_MSG	"IDS_MF_POP_MEMORY_FULL"
#define STR_MP_DISCONNECT_DEVICE                "IDS_DLNA_POP_DISCONNECTED_FROM_PS_CHECK_THE_NETWORK_STATUS_AND_THE_CONNECTED_DEVICE"

#define STR_MP_1_PLAYLIST				"IDS_MUSIC_BODY_1_PLAYLIST"
#define STR_MP_PD_PLAYLISTS				"IDS_MUSIC_BODY_PD_PLAYLISTS"
#define STR_MP_1_ALBUM					"IDS_MUSIC_BODY_1_ALBUM_M_MUSIC"
#define STR_MP_PD_ALBUMS				"IDS_MUSIC_BODY_PD_ALBUMS"
#define STR_MP_1_ARTIST					"IDS_MUSIC_BODY_1_ARTIST"
#define STR_MP_PD_ARTISTS				"IDS_MUSIC_BODY_PD_ARTISTS"
#define STR_MP_1_FOLDER					"IDS_MUSIC_BODY_1_FOLDER"
#define STR_MP_PD_FOLDERS				"IDS_MUSIC_BODY_PD_FOLDERS"
#define STR_MP_1_GENRE					"IDS_MUSIC_BODY_1_GENRE"
#define STR_MP_PD_GENRE					"IDS_MUSIC_BODY_PD_GENRES"
#define STR_MP_SUGGESTION_STR	                        "IDS_MUSIC_HEADER_SUGGESTIONS_FOR_YOU"

#define STR_MS_BASIC                                    "IDS_MUSIC_TAB4_BASIC_M_EQUALIZING"
#define STR_MS_INSTRUMENT                               "IDS_MUSIC_BODY_INSTRUMENT"
#define STR_MS_TREBLE                                   "IDS_MUSIC_BODY_TREBLE_M_EQUALISER"
#define STR_MS_BASS                                     "IDS_MUSIC_BODY_BASS_M_EQUALISER"
#define STR_MS_VOCAL                                    "IDS_MUSIC_BODY_VOCAL_M_SOUNDEFFECT"
#define STR_MS_TUBE_AMP_EFFECT                          "IDS_MUSIC_OPT_TUBE_AMP_EFFECT"
#define STR_MS_VIRTUAL                                  "IDS_MUSIC_OPT_VIRTUAL_71_CH"
#define STR_MS_SMALL_ROOM                               "IDS_MUSIC_HEADER_SMALL_ROOM_M_REVERB_ABB"
#define STR_MS_LARGE_ROOM                               "IDS_MUSIC_HEADER_LARGE_ROOM_M_REVERB_ABB"
#define STR_MS_CONCERT_HALL                             "IDS_MUSIC_BODY_CONCERT_HALL_M_SOUNDEFFECT"
#define STR_MS_NO_EFFECT_CONTENT                        "IDS_MUSIC_SBODY_NO_EFFECTS"
#define STR_MS_NO_TUBE_AMP_CONTENT                      "IDS_MUSIC_BODY_SIMULATES_THE_TIMBRE_OF_A_TUBE_AMP_ABB"
#define STR_MS_NO_VIRTUAL_CONTENT                       "IDS_MUSIC_BODY_SIMULATES_THE_EFFECT_OF_VIRTUAL_71_CHANNEL_SURROUND_SOUND_ABB"
#define STR_MS_NO_LARGE_ROOM_CONTENT                    "IDS_MUSIC_BODY_SIMULATES_THE_REVERB_OF_A_LARGE_ROOM_EG_A_THEATRE_ABB"
#define STR_MS_NO_SMALL_ROOM_CONTENT                    "IDS_MUSIC_BODY_SIMULATES_THE_REVERB_OF_A_SMALL_SPACE_EG_A_STUDIO_ABB"
#define STR_MS_NO_CONCERT_HALL_CONTENT                  "IDS_MUSIC_BODY_SIMULATES_THE_REVERB_OF_A_CONCERT_HALL_ABB"
#define STR_MS_THREE_D                                  "IDS_MUSIC_BUTTON_3D_CHN"
#define STR_MS_CLARITY                                  "IDS_MUSIC_BODY_CLARITY_M_SOUNDEFFECT"
#define STR_MS_THREE_D                                  "IDS_MUSIC_BUTTON_3D_CHN"
#define STR_MS_RESET                                    "IDS_MUSIC_BUTTON_RESET"

#define STR_MS_ADVANCED                                 "IDS_ST_BODY_ADVANCED"
#define STR_MS_NONE                                     "IDS_ST_BODY_NONE"

#define STR_MS_CLASSIC_TYPE     "IDS_MUSIC_BODY_CLASSIC"
#define STR_MS_ROCK_TYPE	"IDS_MUSIC_BODY_ROCK"
#define STR_MS_NORMAL_TYPE	"IDS_MUSIC_BODY_SOUNDEFFECTS_NORMAL"
#define STR_MS_JAZZ_TYPE	"IDS_MUSIC_BODY_JAZZ"
#define STR_MS_POP_TYPE	        "IDS_MUSIC_BODY_POP"
#define STR_MS_AUTO_TYPE	"IDS_MUSIC_BODY_AUTO"
#define STR_MS_BASIC_TAB        "IDS_MUSIC_TAB4_BASIC_M_EQUALIZING"
#define STR_MS_BASS_TYPE        "IDS_MUSIC_BODY_BASS_M_EQUALISER"
#define STR_MS_TREBLE_TYPE 	"IDS_MUSIC_BODY_TREBLE_M_EQUALISER"
#define STR_MS_INSTRUMENT_TYPE 	"IDS_MUSIC_BODY_INSTRUMENT"
#define STR_MS_VOCAL_TYPE 	"IDS_MUSIC_BODY_VOCAL_M_SOUNDEFFECT"
#define STR_MS_EFFECT_TITLE 	"IDS_MUSIC_BODY_EFFECT"
#define STR_MS_RESET_BUTTON     "IDS_MUSIC_BUTTON_RESET"
#define STR_MS_CLARITY_TYPE     "IDS_MUSIC_BODY_CLARITY_M_SOUNDEFFECT"
#define STR_MS_3D_TYPE          "IDS_MUSIC_BUTTON_3D_CHN"

#define STR_MP_RECOMMENDATION_UNSUPPORT  "IDS_MUSIC_POP_AUTO_RECOMMENDATION_DOES_NOT_SUPPORT_THIS_AUDIO_FILE"
#define STR_MP_PLAYER_UNSUPPORT  "IDS_MUSIC_POP_SORRY_THE_PLAYER_DOES_NOT_SUPPORT_THIS_TYPE_OF_AUDIO_FILE"
#define STR_MP_STOP	        "IDS_COM_SK_STOP"
#define STR_MP_SCAN		"IDS_COM_BUTTON_SCAN"
#define STR_MP_HEADPHONE_NO_CONNECT "IDS_MUSIC_TPOP_SOUND_EFFECTS_ONLY_AVAILABLE_WHILE_HEADPHONES_CONNECTED"
#define STR_MP_VIA_SCREEN_MIRRORING "IDS_DLNA_OPT_VIA_SCREEN_MIRRORING_ABB"
#define STR_MP_VIA_HOME_NETWORK     "IDS_DLNA_OPT_VIA_HOME_NETWORK_ABB"

#define STR_MP_ONE_TRACK_DETELED    "IDS_MUSIC_POP_THIS_TRACK_WILL_BE_DELETED"
#define STR_MP_PLURAL_TRACKS_DETELED    "IDS_MUSIC_POP_THE_SELECTED_TRACKS_WILL_BE_DELETED"
#define STR_MP_ALL_TRACKS_DETELED    "All tracks will be deleted."

#define STR_MP_ONE_ARTIST_DETELED    "IDS_MUSIC_POP_THIS_ARTIST_WILL_BE_DELETED"
#define STR_MP_PLURAL_ARTISTS_DETELED    "IDS_MUSIC_POP_THE_SELECTED_ARTISTS_WILL_BE_DELETED"
#define STR_MP_ALL_ARTISTS_DETELED    "IDS_MUSIC_POP_ALL_ARTISTS_WILL_BE_DELETED"

#define STR_MP_ONE_FOLDER_DETELED    "IDS_MUSIC_POP_THIS_FOLDER_WILL_BE_DELETED"
#define STR_MP_PLURAL_FOLDERS_DETELED    "IDS_MUSIC_POP_THE_SELECTED_FOLDERS_WILL_BE_DELETED"
#define STR_MP_ALL_FOLDERS_DETELED    "IDS_MUSIC_POP_ALL_FOLDERS_WILL_BE_DELETED"

#define STR_MP_ONE_ALBUM_DETELED    "IDS_MUSIC_POP_THIS_ALBUM_WILL_BE_DELETED"
#define STR_MP_PLURAL_ALBUMS_DETELED    "IDS_MUSIC_POP_THE_SELECTED_ALBUMS_WILL_BE_DELETED"
#define STR_MP_ALL_ALBUMS_DETELED    "IDS_MUSIC_POP_ALL_ALBUMS_WILL_BE_DELETED"

#define STR_MP_ONE_PLAYLIST_DETELED    "IDS_MUSIC_POP_THIS_PLAYLIST_WILL_BE_DELETED"
#define STR_MP_PLURAL_PLAYLISTS_DETELED    "IDS_MUSIC_POP_THE_SELECTED_PLAYLISTS_WILL_BE_DELETED"
#define STR_MP_ALL_PLAYLISTS_DETELED    "IDS_MUSIC_POP_ALL_PLAYLISTS_WILL_BE_DELETED"

//3 Need to be translated

#define STR_MP_ITEMS_CAN_BE_SELECTED_UP_TO_PD "IDS_HS_BODY_SELECT_UP_TO_PD_ITEMS"
#define STR_MP_SELECT_ITEMS_UP_TO_PD	"Select items up to %d"
#define STR_MP_SHAZAM		"IDS_COM_SK_DOWNLOAD"
#define STR_MP_GALLERY		"IDS_COM_BODY_GALLERY"
#define STR_MP_UPDATE_ALBUM_ART	"IDS_MUSIC_UPDATE_ALBUMART"


#define STR_MP_HDMI			"IDS_VPL_OPT_HDMI"


#define 	STR_MP_DROPBOX "IDS_MF_BODY_DROPBOX_ABB"

///can not find
#define STR_MP_MIRRORING	"Mirroring"
#define STR_MP_USB_AUDIO 	"USB Audio"
#define STR_PREVIOUSLY_ADDED    "Previously added"     //not used..
#define STR_MP_THE_APP_CONTROL_IS_DISABLED "Bluetooth is disabled. To enable it, go to Privacy setting and allow the service to be used in application"
#define STR_MP_THE_ACCOUNT_SVC_IS_DISABLED "Account is disabled. To enable it, go to Privacy setting and allow the service to be used in application"

#define MP_MENU_FID "mp_menu_fid"
#define MP_MENU_GROUP_ITEM_HANDLER    	"mp_menu_group_item_handler"

#define STR_MP_SET_AS_FROM_BEGIN	"IDS_MUSIC_BUTTON_FROM_THE_BEGINNING"
#define STR_MP_SET_AS_AUTO_RECOMMEND	"IDS_MUSIC_BUTTON_AUTO_RECOMMENDATIONS"
#define STR_MP_SET_AS_PHONE_RINGTONG	("IDS_MUSIC_POP_PHONE_RINGTONE")
#define STR_MP_SET_AS_ALARM_TONE		("IDS_MUSIC_OPT_SETAS_ALARM_TONE")
#define STR_MP_SET_AS_CALLER_RINGTONG	("IDS_MUSIC_OPT_SETAS_CALLER_RINGTONE")
#define STR_MP_SET_AS_RECOMMENDED_TXT	"IDS_PB_BODY_AUTO_RECOMMENDATIONS_CAN_EXTRACT_THE_HIGHLIGHTS_FROM_SOUND_FILES"

#define MP_SCREEN_READER_TAB "IDS_CAM_BODY_TAB_T_TTS"
#define MP_SCREEN_READER_DOUBLE_TAP "IDS_ST_BODY_DOUBLE_TAP_TO_MOVE_TO_CONTENT_T_TTS"
#define MP_SCREEN_READER_DOUBLE_TAP_PLAY "double tap to play"
#define MP_SCREEN_READER_CP "IDS_ST_BODY_A_CONTEXTUAL_POP_UP_IS_OPEN_DOUBLE_TAP_TO_CLOSE_IT_T_TALKBACK"
#define MP_SCREEN_READER_SELECTED "IDS_COM_BODY_SELECTED"
#define MP_SCREEN_READER_SELECT_ALL "IDS_MUSIC_BODY_SELECT_ALL"

#define MP_SCREEN_READER_ITEM_SELECTED "IDS_COM_BODY_SELECT_ALL"
#define MP_SCREEN_READER_ITEM_UNSELECTED "IDS_IMGE_BODY_UNSELECT_ALL"
#define MP_SCREEN_READER_SEARCH "IDS_MUSIC_OPT_SEARCH_ABB"
#define MP_SCREEN_READER_DMR    "IDS_MUSIC_BODY_NEARBY_DEVICES"
#define MP_SCREEN_BUTTON "IDS_CAM_BODY_BUTTON_T_TTS"

#define MP_POPUP_LOADING "IDS_ST_BODY_LOADING_ING"
#define MP_POPUP_DELETING "IDS_MUSIC_POP_DELETING"

//can not find
#define MP_SCREEN_READER_EQ_UP       "EQ part value increase to band 1 %2.1f db band 2 %2.1f db band 3 %2.1f db band 4 %2.1f db band 5 %2.1f db band 6 %2.1f db band 7 %2.1f db band 8 %2.1f db"
#define MP_SCREEN_READER_EQ_DOWN     "EQ part value decrease to band 1 %2.1f db band 2 %2.1f db band 3 %2.1f db band 4 %2.1f db band 5 %2.1f db band 6 %2.1f db band 7 %2.1f db band 8 %2.1f db"
#define MP_SCREEN_READER_EXTEND_UP   "Extended part value increase to 3D %1.1f Bass %1.1f Room size %1.1f Reverb Level %1.1f Clarity %1.1f"
#define MP_SCREEN_READER_EXTEND_DOWN "Extended part value decrease to 3D %1.1f Bass %1.1f Room size %1.1f Reverb Level %1.1f Clarity %1.1f"

#define MP_SCREEN_READER_HELP_DOWN	"Double click to show help popup"


//For tts string
#define MP_TTS_PREVIOUS_BUTTON "IDS_COM_BODY_PREVIOUS"
#define MP_TTS_PLAY_BUTTON "IDS_COM_SK_PLAY_ABB"
#define MP_TTS_PAUSE_BUTTON "IDS_COM_BODY_PAUSE"
#define MP_TTS_NEXT_BUTTON "IDS_COM_SK_NEXT"
#define MP_TTS_CLOSE_BUTTON "IDS_COM_BODY_CLOSE"
#define MP_TTS_FAVOURITE_BUTTON "IDS_MUSIC_BODY_MARKED_AS_A_FAVOURITE"

#define MP_TTS_UNFAVOURITE_BUTTON "IDS_MUSIC_BODY_NOT_MARKED_AS_A_FAVOURITE"


#define MP_TTS_VOLUME_BUTTON "IDS_MUSIC_BODY_SETTINGS_VOLUME"
#define MP_TTS_REPEAT_OFF_BUTTON "IDS_MUSIC_BODY_REPEAT_OFF"
#define MP_TTS_REPEAT_ALL_BUTTON "IDS_MUSIC_BODY_PLAYINGREPEAT_REPEAT_ALL"
#define MP_TTS_SHUFFLE_OFF_BUTTON "IDS_MUSIC_BODY_SHUFFLE_OFF"
#define MP_TTS_SHUFFLE_ON_BUTTON "IDS_MUSIC_BODY_SHUFFLE_ON"
#define MP_TTS_REPEAT_ONE_BUTTON "IDS_ST_BODY_REPEAT_ONE"
#define MP_TTS_QUEUE_BUTTON "IDS_MUSIC_BODY_PLAYLIST"
#define MP_TTS_MUSIC_PLAYER_BUTTON "IDS_MUSIC_BODY_MUSIC_PLAYER"
#define MP_TTS_SOUNDALIVE_BUTTON  "IDS_MUSIC_OPT_SOUNDALIVE"

#define MP_TTS_PROGRESS_PLAYING "IDS_COM_SK_PLAY_ABB"
#define MP_TTS_PROGRESS_TOTAL "IDS_MH_BODY_TOTAL"

#endif
